### ISSUE TITLE
image import at the server side

### ISSUE THREAD

**Issue by ryanwang520** [ayroblu/ssr-create-react-app-v2#9]
Hi! 

This SSR approach works very well for me except that there is no such a simple way to handle image import at the server side like `import Logo from './logo.png'` without setup a webpack dev server. Besides, how can we use the exact `file-loader` config used by `create-react-app` for SSR , or we just have to eject it to handle this stuff? Any thought on this?

Thanks.

**Comment by ayroblu** [comment]
Yeah, you can just add it to the babel register if you want to do that I think. There's no elegant solution here, though it should be noted that for relatively large images, you should be hosting them in a static folder and using image names rather than including them in base64 strings for caching reasons

**Comment by bondom** [comment]
@ayroblu Please explain me where from is required `babel-register` I try to find where it is installed, I don't understand why this works..

**Comment by JaosnHsieh** [comment]
@ryanwang520 do you fix it?
I tried to put babel-plugin-transform-react-jsx-img-import to babel-register but the image url is still object Object though.
